name: Update I2P Data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allow manual trigger

env:
  IP_V6: ${{ secrets.IPV4 }}
  IP_V4: ${{ secrets.IPV6 }}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Update
        run: bash i2p.sh
        
      - name: Force add and commit
        run: |
          git config --local user.email "scriptzteam@gmail.com"
          git config --local user.name "scriptzteam"
          git add -A
          git status
          if git status --porcelain | grep -q '^?? \|^A  \|^M  '; then
            echo "Changes detected, committing..."
            git commit -m "Update"
            git push
          else
            echo "No changes to commit"
          fi
